### ISSUE TITLE
Change of color selection automatically swaps current tool to pencil

### ISSUE THREAD

**Issue by VisenDev** [foxnne/pixi#24]

**Comment by foxnne** [comment]
I'm not opposed to changing this behavior, but the right-click color select changing the tool is intentional. If you select empty space (full transparency), the eraser tool is selected. I felt this made drawing much quicker as you can quickly sample a color, it automatically switches to the correct layer and pencil tool, and you can continue drawing. I realize this is different than other drawing programs however.

**Comment by VisenDev** [comment]
> I felt this made drawing much quicker as you can quickly sample a color, it automatically switches to the correct layer and pencil too

This is fine, it was causing some trouble for me when I was trying to use the bucket tool to recolor an image. Everytime I selected a new color from the palette, it would change from bucket to pencil. That was my logic

Suggested behavior: If you are using a tool already that outputs colors, and you select a new color, you keep that tool selected. Otherwise go to pencil tool?

**Comment by BrookJeynes** [comment]
Hey team, I'm gonna have a go at solving this issue.

**Comment by foxnne** [comment]
Brook's solution should close this issue :) let me know behavior is not as desired
