### ISSUE TITLE
add compiled binaries?

### ISSUE THREAD

**Issue by jestarray** [foxnne/pixi#59]
add compiled binaries to releases :face_holding_back_tears:

**Comment by Atomk** [comment]
Since I see a "sponsors" page, [Asesprite](https://github.com/aseprite/aseprite) and [Armor Paint](https://github.com/armory3d/armortools) are open source applications that provide the binaries on stores to fund development. That's of course a different philosophy compared to just relying on donations, and a bit more ambitious.

**Comment by foxnne** [comment]
That's the goal, but simply put, pixi is just not to this point yet. It's still mainly just myself adding features as I need them, and the program still doesn't support many basic operations (a selection tool is sorely needed right now and I'm currently looking into this).

At the point where I feel like pixi is in a good stable position and would be fair to post binaries for anyone to use, I will tag a release and get binaries up here as well as on itch or something similar.

**Comment by gingerbeardman** [comment]
Thanks, I understand

**Comment by foxnne** [comment]
I've added some CI that builds and uploads artifacts on the following platforms:
- x86_64-Windows
- x86_64-Linux
- x86_64-MacOS
- Arm64-MacOS

I will also look into packaging the app and hopefully someday having an actual release.
